sudo: required
services:
  - docker

before_install:
  - gem install bundler --pre
  - docker build -t radisav/docker-react -f Dockerfile.dev .

script:
  - docker run radisav/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  name: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-496055662330"
  bucket_path: "docker-react"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
